### ISSUE TITLE
console no response when install windows xp and windows 7

### ISSUE THREAD

**Issue by arjing** [vatesfr/xo#57]
i used console to install windows xp and windows 7。In the process of installation，the console will stop responsing（win7 after the “starting windows” screen）。And there is no error output。

**Comment by olivierlambert** [comment]
Should be working since new direct console connection

**Comment by arjing** [comment]
still not working.
when i install win7/windows2008 r2 . the console will stop working, and the client xen admin console stop working too。 i check the host , found that the  qume is quited.

**Comment by olivierlambert** [comment]
@arjing that was indeed a QEMU issue, that was fixed by Citrix (see the story here: https://xen-orchestra.com/blog/bug-hunt-with-citrix/ ). You need to install the patch.

**Comment by arjing** [comment]
problem solved,Thank you very much
